- Content.Shared/Maps/ContentTileDefinition.cs
- Resources/Prototypes/_CP14/Tiles/base.yml
- Resources/Prototypes/_CP14/Tiles/natural.yml
- Resources/Prototypes/_CP14/Tiles/produced.yml
The tile spawn menu now contains only those tiles that are used by the project.
> Tile menu filter

- Resources/Prototypes/_CP14/Entities/Structures/Flora/floorWater.yml
Fixes #189 
Small fix, that allows to draw water from the floorwater.
Маленький фикс, позволяющий черпать воду из floorwater.
Счастливый обладатель бесконечных запасов воды, фото в цвете:
> Fix can't draw from the water on the floor

- Content.Shared/_CP14/Wallmount/CP14WallRequired.cs
- Content.Shared/_CP14/Wallmount/CP14WallmountComponent.cs
- Content.Shared/_CP14/Wallmount/CP14WallmountSystem.cs
- Resources/Locale/en-US/_CP14/construction/wall-required.ftl
- Resources/Locale/ru-RU/_CP14/construction/wall-required.ftl
- Resources/Prototypes/Tiles/space.yml
- Resources/Prototypes/_CP14/Entities/Structures/Furniture/wallmount.yml
- Resources/Prototypes/_CP14/Recipes/Construction/furniture.yml
wallmount objects are now automatically parenting to the wall, destroyed with it, and move with it. 
Added a new building condition to allow wallmounts to be built only at the wall\window
fix torch construction preview
> Wallmount update

- Content.Server/_CP14/Temperature/CP14FireSpreadSystem.cs
Fixes #277 by ignoring the ignition caused by items inside container (in that issue there were logs inside bonfire).
Items inside containers have zero coordinates, so we shouldn't use them in the fire spread system. Maybe we should somehow get map coordinates of the item.
Fixes #277
> [Fix] Do not ignite zero coordinates because of items inside containers.

- Content.Server/Speech/EntitySystems/StutteringSystem.cs
CHANGE WIZARD's CODE. Stuttering on bloodloss for russian localization, made as it was on Corvax.
Though, better to be fixed on wizard's side by moving this regex into .ftl file
Fixes https://github.com/crystallpunk-14/crystall-punk-14/issues/291
> stuttering on bloodloss and electricity damage

- Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
- Content.Server/_CP14/MeleeWeapon/Components/CP14MeleeSelfDamageComponent.cs
- Content.Server/_CP14/MeleeWeapon/Components/CP14SharpenedComponent.cs
- Content.Server/_CP14/MeleeWeapon/Components/CP14SharpeningStoneComponent.cs
- Content.Server/_CP14/MeleeWeapon/EntitySystems/CP14MeleeSelfDamageSystem.cs
- Content.Server/_CP14/MeleeWeapon/EntitySystems/CP14SharpeningSystem.cs
- Content.Server/_CP14/Skills/CP14SkillSystem.cs
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/base.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/battleHammer.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/lightHammer.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/mace.yml
Content.Server/MeleeWeapon разделен на две подпапки: `Component` и `EntitySystems`
Теперь оружию с компонентом `CP14MeleeSelfDamage` наносится урон. 
Добавлен прототип `CP14BaseWeaponSelfDamage` для оружием урона по самому себе от ударов.
По умолчанию, оружия хватает на 50 ударов.
Решает #85
https://github.com/user-attachments/assets/a4925cc7-4278-44fd-b3cb-fc0549608eea
> Selfdamage for melee (#85)

- Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/battleHammer.yml
- Resources/Prototypes/_CP14/Entities/Structures/Flora/floorWater.yml
- Resources/Prototypes/_CP14/Entities/Structures/Walls/natural.yml
- Resources/Prototypes/_CP14/Recipes/Construction/walls.yml
Removed “bruh” descriptions from the entity and localization file
Убраны "брух" описания из энтити и файла локализации
[issue resolution](https://github.com/crystallpunk-14/crystall-punk-14/issues/207)
> Remove "bruh" desc

- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/produce.yml
`ItemHeftyBase` - Новый parrent для того чтобы работало корректно бросание помидора, вместимость жидкостей изменена из `8 -> 12` поскольку нужно место и для помидорного сока, `Destructible` чтобы при броске помидора он разваливался, ну то-есть бился. `Tag` - Нужно просто для удобного поиска по тэгам в спавне.
`  - type: FoodSequenceElement
entries:
Skewer: TomatoSkewer
Burger: Tomato
Taco: Tomato`
`FoodSequenceElement` был добавлен просто для готовки или для чего-то другого. Впрочем это есть в Space Station 14 оригинальной, ну пусть и будет в этом коде. Не мешает. `Extractable` можно извлечь сок из помидора, как не странно 10 унций. `DamageOnHighSpeedImpact` для получения урона в 1 единицу. `Damageable` для звука разбития помидора.
Помидоры теперь как и в реальной жизни, то-есть могут …
> Add throwing tomatoes and fix

- Resources/Prototypes/_CP14/Entities/Structures/Storage/Crates/crates.yml
The crates are heavier now and you can't just pull them around.
Ящики теперь тяжелее и так просто их не потягаешь.
> Heavy crates

- Resources/Prototypes/_CP14/Entities/Clothing/Cloak/Roles/alchemist.yml
- Resources/Prototypes/_CP14/Entities/Clothing/Cloak/Roles/blacksmith.yml
- Resources/Prototypes/_CP14/Entities/Clothing/Cloak/sort_later.yml
- Resources/Prototypes/_CP14/Entities/Clothing/base.yml
- Resources/Prototypes/_CP14/Entities/Objects/Materials/simple.yml
- Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/vials.yml
- Resources/Prototypes/_CP14/Entities/Objects/Tools/flint.yml
- Resources/Prototypes/_CP14/Entities/Objects/Tools/scissors.yml
- Resources/Prototypes/_CP14/Entities/Objects/Tools/sharpening_stone.yml
- Resources/Prototypes/_CP14/tags.yml
Adds a small container to the blacksmith's apron and alchemist's cloak with a whitelist.
Добавляет небольшой контейнер в фартук кузнеца и плащ алхимика с белым листом.
Blacksmiths' aprons are useless and are only decorative in nature, it will now make sense for blacksmiths to wear them on the job. Space for several vials has been added to the alchemists' cloak, which seems authentic and useful.
Фартуки кузнецов бесполезны и имеют только декоративный характер, теперь в них будет смысл носить кузнецам на рабочем месте. В плащ алхимиков добавлено место для нескольких склянок, что кажется аутентичным и полезным.
> Apron containers

- Resources/Prototypes/_CP14/Entities/Mobs/NPC/animals.yml
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/meat.yml
Changed the balance of the rabbit meat and it can now be used to make a meat pie too.
Изменил баланс мяса кроллика, и теперь его тоже можно использовать для готовки мясного пирога.
Rabbits are plentiful and their meat can only be used to a limited extent. Now they can be used to make meat pies.
Кроликов много, а мясо их использовать можно лишь ограничено. Теперь их можноиспользовать для готовки мясных пирогов.
> The rabbit is also a pie

- Resources/Prototypes/_CP14/Entities/Mobs/Species/zombie.yml
Now zombies can be pacifists.
Теперь зомби могут быть пацифистами.
Fix #947
> Zombi pacified

- Resources/Maps/_CP14/comoss_d.yml
Передвинул бочки в подвале Алхимика 2
Moved barrels in basement of Alchemist 2.
Бочка стояла не по центру и раундстартом поднималась на вверх закрывая проход. Это смешно, но раздражает.
The barrel was placed off-center and roundstarted went upstairs and blocked the passage. Funny, but annoying
Was:
Became:
> [Fix]Barrel in comoss_d

- Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/tools.yml
Максимальный обьем шприца для выбора теперь 10u, а не 15u.
Maximum syringe transfer amount is now 10u instead of 15u.
Максимум шприца - 10u.
Maximum syringe volume is 10u.
> [Fix] CP14Syringe transfer amount fix

- Resources/Prototypes/_CP14/Entities/Objects/Specific/Thaumaturgy/essence.yml
- Resources/Prototypes/_CP14/Entities/Structures/Flora/Crystal/elemental.yml
- Resources/Prototypes/_CP14/Entities/Structures/Flora/Crystal/shards.yml
- Resources/Prototypes/_CP14/Entities/Structures/Specific/Thaumaturgy/essence_nodes.yml
- Resources/Prototypes/_CP14/Reagents/magic_essence.yml
Aer and energia was recolored
Because aer and ordo was almost same color; energia was recolored cuz yellow is not cool
aer energia ordo
> Aer and energia recolor

- Content.Server/_CP14/Chemistry/ReagentEffect/CP14ManaChange.cs
- Resources/Prototypes/_CP14/Reagents/target_effects.yml
Теперь, востановление маны работает как у других веществ, и при метаболизме 0.05 лечит 1.5 в итоге выйдет 30 маны.
Now, mana potion works like other , and with metabolism 0.05 heals 1.5, you'll end up with 30 mana.
Fix #1032
> [Fix]Mana heal/damage potion fix

- Resources/Prototypes/_CP14/Entities/Structures/Floor/floorWater.yml
```CP14FloorWaterOptimized``` больше нельзя заспавнить через панель.
``CP14FloorWaterOptimized`` can no longer be spawned from panel.
Fix #1093
> [Fix]CP14FloorWaterOptimized fix

- Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Breastplate/chainmail.yml
- Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Breastplate/cuirass.yml
- Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Breastplate/infantry_cuirass.yml
- Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/armor.yml
Armour now gives a modifier to the cost of using spells. Iron armour gives the most cost, gold armour on the contrary gives less cost. Mithril armour, on the contrary, makes spells cheaper.
Броня теперь дает модификатор к стоимости использования заклинаний. Железные доспехи дают больше затрат, золотые, наоборот, меньше. Мифриловая броня, наоборот, удешевляет заклинания.
Those who develop magic more will now have to do more thinking and balancing of their equipment, rather than just taking all the coolest stuff and essentially being no different from a warrior. 
Тем, кто больше развивает магию, теперь придется больше думать и балансировать свое снаряжение, а не просто брать все самое крутое и по сути ничем не отличаться от воина.
> Magic modifier armour

- Resources/Prototypes/_CP14/Entities/Mobs/Player/DemiplaneAntag/Skeletons/T1.yml
- Resources/Prototypes/_CP14/Entities/Mobs/Player/DemiplaneAntag/Skeletons/T2.yml
исправлены незамеченные ошибки из https://github.com/crystallpunk-14/crystall-punk-14/pull/1145#issue-2975156252 а именно:
- у Т1 лучника убран навык в атлетике
- Т2 спавнера скелетов теперь невидимые
Я дурак не проверил всё до конца, извините
> sttopid skeleton fixes

- Resources/Prototypes/_CP14/Entities/Structures/Walls/ore_veins.yml
- Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Reward/ores.yml
Теперь выпадает немного больше медной и железной руды, а так же увелчино количество возможного спавна рудных стен в каменных жилах
После изменения баланса количества жил и руды в ней, в целом руды стало намного меньше, что редко окупает поход в демиплан или вообще идет в минус.
> Ребаланс выпадения руды

- Content.Client/_CP14/UserInterface/Systems/Skill/CP14SkillUIController.cs
- Content.Client/_CP14/UserInterface/Systems/Skill/Window/CP14SkillWindow.xaml
- Content.Shared/Preferences/Loadouts/LoadoutPrototype.cs
- Content.Shared/Station/SharedStationSpawningSystem.cs
- Content.Shared/_CP14/Skill/CP14LearnSkillsSpecial.cs
- Content.Shared/_CP14/Skill/CP14SharedSkillSystem.cs
- Content.Shared/_CP14/Skill/Components/CP14SkillStorageComponent.cs
- Resources/Locale/en-US/_CP14/skill/ui.ftl
- Resources/Locale/ru-RU/_CP14/skill/ui.ftl
- Resources/Prototypes/_CP14/Entities/Mobs/Species/elf.yml
- Resources/Prototypes/_CP14/Entities/Mobs/Species/silva.yml
- Resources/Prototypes/_CP14/Entities/Mobs/Species/tiefling.yml
- Resources/Prototypes/_CP14/Loadouts/Jobs/guard.yml
- Resources/Prototypes/_CP14/Loadouts/Jobs/guildmaster.yml
- Resources/Prototypes/_CP14/Loadouts/role_loadouts.yml
- Resources/Prototypes/_CP14/Skill/blacksmithing.yml
- Resources/Prototypes/_CP14/Skill/hydrosophistry.yml
- Resources/Prototypes/_CP14/Skill/martial_arts.yml
- Resources/Prototypes/_CP14/Skill/thaumaturgy.yml
Скиллы теперь могут быть "врожденными" и не учитываться в рассчетах потраченных очков памяти.
"Врожденные" скиллы теперь могут идти от трех источников:
- Расы: 
- Тифлинги получили Т1 и Т2 пирокинетику бесплатно
- Сильвы получили Т1 и Т2 жизнетворения
- Эльфы получили Т1 и Т2 метамагию
- Лоадаут
- Авантюристы могут выбирать стартовую экипировку оружия, что дает врожденное владение им
- Роли
- Кузнец имеет бесплатно все скиллы кузнечного дела
- Алхимик имеет бесплатное алхимическое зрения
- Подмастерье имеет часть кузнечных навыков и алхимическое зрение
Все навыки которые раньше нельзя было изучить (мастерство оружия, кузнечное дело, алхимия) теперь можно изучать за очки памяти
--- 
Skills can now be “innate” and not counted in the calculation of memory points spent.
“Innate” skills can …
> Species free innate skill

- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Smokeables/Pipes/pipe.yml
added hideCaution to BaseSmokingPipe
Smoking pipe is intended to be lit, but currently gives red warning text when attempting to ignite. Similar ignitable items like torches already have this behavior.
> Changed smoking pipe to not warn when igniting

- Content.Server/_CP14/DemiplaneTraveling/CP14StationDemiplaneMapSystem.cs
- Content.Shared/_CP14/Demiplane/Prototypes/CP14SpecialDemiplanePrototype.cs
- Content.Shared/_CP14/Workbench/Requirements/MaterialResource.cs
- Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_ice.yml
- Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_magma.yml
- Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Reward/rooms.yml
- Исправлен баг с излишним удалением скрапа при переплавке в слитки
- Исправлен баг с дубликацией модификаторов на карте демипланов
---
- Fixed a bug with excessive removal of scrap when melting into ingots
- Fixed a bug with duplicate modifiers on the demiplane map
> Critical bugfixes

- Resources/Prototypes/_CP14/Entities/Structures/Doors/Locked/guildmaster.yml
- Resources/Prototypes/_CP14/Entities/Structures/Specific/Demiplanes/round_end.yml
- Resources/Prototypes/_CP14/Maps/Frigid_Coast.yml
- Resources/Prototypes/_CP14/Maps/comoss.yml
- Resources/Prototypes/_CP14/Roles/Jobs/Artisan/alchemist.yml
- Resources/Prototypes/_CP14/Roles/Jobs/Artisan/blacksmith.yml
- Resources/Prototypes/_CP14/Roles/Jobs/Mercenary/guildmaster.yml
- Resources/Prototypes/_CP14/Roles/Jobs/Traders/merchant.yml
Эти 2 роли на текущий момент полностью сломаны и не играбельны. Для незнающих новичков это может быть фрустрирующий опыт. Роли убраны для выбора в меню создания персонажа до их переработки в будущем. 
Двери к кристаллу демиплана теперь раундстартом открыты.
Подготовка более-менее комфортной ситуации в билде перед запуском английского ЗБТ
---
These 2 roles are currently completely broken and unplayable. This can be a frustrating experience for unfamiliar newbies. The roles have been removed for selection in the character creation menu until they are redesigned in the future. 
The doors to the demiplane crystal are now open from roundstart.
Preparing a more or less comfortable build situation before launching the English CBT
> Remove Guildmaster & Merchant roles

- Resources/Prototypes/_CP14/Entities/Objects/Keys/tools.yml
Rotated the inventory Key File by 45 degrees to match the original sprite while in inventory.
Intended to solve [Issue 1237](https://github.com/crystallpunk-14/crystall-punk-14/issues/1237)
A small change, my first PR.
Before
After
> Rotated Keyfile

- Resources/Locale/en-US/_CP14/nutrition/food-sequence.ftl
- Resources/Locale/ru-RU/_CP14/nutrition/food-sequence.ftl
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/cheese.yml
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/dough.yml
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/meat.yml
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/produce.yml
- Resources/Prototypes/_CP14/Recipes/Cooking/food_sequence_element.yml
- Resources/Prototypes/_CP14/tags.yml
The buns can now be used to make sandwichs with different toppings.
Теперь из булок можно делать бутерброды с разной начинкой.
More content for tavernkeepers.
Больше контента для тавернщиков.
> Tavernkeeper's Sandwich

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_shards.yml
Changes ice shard's piercing damage from 6 to 2.
Ice shard has consistently been the best spell main reason for this i think is the bleed stacks it can inflict with the piercing damage, this also nerfs the DPS down to around 10.5 instead of 18.33.
> Ice shard nerf

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/sheep_polymorph.yml
- Resources/Prototypes/_CP14/Skill/healing.yml
Returning the sheep polymorph to the spellcasting branch of healing skins. Also now you can't polymorph corpses.
Возвращение овце-полиморфа в ветку заклинания скилов лечения. Так же теперь нельзя полиморфировать трупов.
It's fun with this spell.
С этим заклинанием весело.
> Polymorph return

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/cure_heat.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/cure_poison.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/cure_wounds.yml
This PR bring some modification to mana cost and healing functions on the basic healing spells (cure wounds/burns/poison).
Mana cost increased from 10 to 12 on all three spells(allowing 2 cast for goblins without burning them to a crisp)
Cure Wounds now staunch some bleeding(from 0 to 5 stacks healed, maximum bleeding stacks are at 15 for reference)
Cure Poison(also known as blood purification) no longer stop bleeding(from 15 to 0) BUT restore more blood(from 15 to 25)
This PR aim to rebalance resource cost of spells with the aim of pushing player to use potions slightly more.(i do not know how to change spell tier availability, nor found healing_staff yalm(i would have increase healing cost from +50% to +100% considering only alchemist own one and are supposed to craft and use potions, …
> Small healing magic rebalance.

- Resources/Prototypes/_CP14/Reagents/target_effects.yml
Made blood healing solution heal 10 bloodloss damage.
Made blood absorption solution deal 3 bloodloss damage.
Currently only spells can heal this kind of damage this should be remedied. Also gives more a reason to carry blood healing potions.
> Add heal/damage to bloodhealing/absorption 

- Resources/Prototypes/_CP14/Entities/Structures/Specific/Economy/cash_converter.yml
Fixes #605, brings CP14CashConverter in line with CP14AlchemySolutionCleaner. That is, no player collision but anchorable with tables and doesn't go through walls. Someone with more experience with fixtures may be able to help with this.
Cash converters are intended to be anchor able on tables as shown by mapping and the issue.
**Changelog**
:cl:
- fix: Cash converters can be anchored on tables
> Changed cashconverter to be anchorable on tables

- Content.Shared/_CP14/MagicSpell/Spells/CP14SpellArea.cs
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/hell_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/heal_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/peace_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/speed_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Meta/mana_ballade.yml
**Changelog**
:cl:
- tweak: Music magic no longer applies the effect on the musician. Tieflings with Hell Ballad are now OP
- tweak: The radius of action of the peace ballad has been increased by 2 times and the maximum number of entities that can be affected has been increased from 4 to 8
- tweak: The speed increase from the speed ballad is increased by 5%
> Ballade magic rework

- Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/tools.yml
Dropper size is back to tiny, same as upstream plus it makes more sense than it's current 2x1.
A dropper should be atleast as small as a small vial since it holds even less reagent.
**Changelog**
> fix(objects): dropper size to tiny

- Content.Server/_CP14/Trading/CP14TradingPlatformSystem.cs
- Content.Shared/_CP14/Trading/CP14AddGlobalReputationSpecial.cs
- Content.Shared/_CP14/Trading/Systems/CP14SharedTradingPlatformSystem.cs
- Resources/Prototypes/_CP14/Roles/Jobs/Traders/merchant.yml
**Changelog**
:cl:
- tweak: All merchants now gain +1 reputation with each faction at the start of the round, greatly expanding their range of goods.
> Starting reputation of merchants

- Content.Server/Speech/EntitySystems/VocalSystem.cs
I removed The initizalition for the Scream Action, wich takes place as soon as the Map is initialization.
In addition the Subsciption To the Local Events For  "OnMapInit" and "Onshutdown" were removed as they are now nolonger used by the Vocal System
#1212
#1214
:cl:
- remove: Removed the scream action from the hotbar. Yelling can still be done through the emotion wheel and chat.
> Removing The Scream Action From The Action Bar

- Resources/Prototypes/_CP14/Recipes/Workbench/Anvil/modular_aventail.yml
- Resources/Prototypes/_CP14/Recipes/Workbench/Anvil/modular_greave.yml
Fixed some misplaced recipes for Aventails and Greaves found in the Anvil
Because how could one learn how to make golden greaves from learning how to smelt and forge copper?
Forgot to grab photo of the misplaced recipes... Oops.
**Changelog**
:cl:
- fix: Iron, Gold and Mithril Aventails recipes to be at their respected metal category
- fix: Iron and Gold Greaves recipes to be at their respected metal category
> Fixed some misplaced recipes for Aventails and Greaves.

- Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/pickaxe.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/rapier.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/skimitar.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/sword.yml
**Changelog**
:cl:
- fix: Copper tools and weapons are now displayed correctly in loadout
> copper loadout fix

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Demigods/Lumera/moon_strike.yml
Added a telegraph to lunar strike, made lunar strikes cooldown 25 seconds, reduced the flash radius on lunar strike to 1.5
lunar strike still too good 
https://github.com/user-attachments/assets/a84eb1e7-07bd-4937-abe9-89d50bfa8300
**Changelog**
:cl:
- add: Added a telegraph to Lunar strike with a cast time of 1 second.
- tweak: Changed Lunar strike to have a cooldown of 25 seconds, decrease the flash radius to 1.5 instead of 2.
> Telegraph on lunar strike.

- Resources/Locale/en-US/_CP14/reagents/meta/consumable/food/ingredients.ftl
- Resources/Locale/en-US/_CP14/reagents/meta/thaumaturgy/precurser.ftl
- Resources/Locale/ru-RU/_CP14/reagents/meta/consumable/food/ingredients.ftl
- Resources/Locale/ru-RU/_CP14/reagents/meta/thaumaturgy/precurser.ftl
- Resources/Prototypes/_CP14/Entities/Mobs/NPC/invisible_whistler.yml
- Resources/Prototypes/_CP14/Entities/Mobs/NPC/mole.yml
- Resources/Prototypes/_CP14/Entities/Mobs/NPC/spider.yml
- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/meat.yml
- Resources/Prototypes/_CP14/Reagents/Consumable/Food/ingredients.yml
- Resources/Prototypes/_CP14/Reagents/blood.yml
Adds its own type of magical blood to monsters, which tends to deal damage with magic depletion but replenishes mana. Also adds a separate nutrient to monster meat that reduces mana but cures mana depletion.
Добавляет монстрам собственный тип магической крови, которая имеет свойство наносить урон магическим истощением, но пополняет ману. Так же добавляет отдельное питательное вещество в мясо монстров, которое уменьшает ману, но лечит манаистощение.
Despite having some special properties, monsters were just like normal animals, having the same blood and meat. Now they have a more unique and special build that can also be used if desired.
Не смотря на некоторые особые свойства, монстры были такие же как и обычные животные, имея ту же кровь и мясо. Теперь они имеют более уникальное и особое …
> Monster blood

- Content.Server/GameTicking/GameTicker.Spawning.cs
- Resources/Locale/en-US/_CP14/game-tiker.ftl
- Resources/Locale/ru-RU/_CP14/game-tiker.ftl
**Changelog**
:cl:
- tweak: Arrival notifications no longer mention the station.
> Arrival notifications no longer mention the station

- Resources/Prototypes/_CP14/Entities/Structures/Specific/Blacksmith/sharpening_stone.yml
added whitelist to sharpening stone
fix #1536 
**Changelog**
:cl:
fix: The blacksmith can no longer sharpen planks at the start of a round.
> Sharpening Stone fix

- Resources/Prototypes/_CP14/Loadouts/Jobs/general.yml
Adds mercenary beret, mercenary shirt and mercenary pants into the general loadout group.
Easy but pain in the ass to craft during a round and it's so drippy. Adventurer is called a "mercenary job" in the menu so why shouldn't we have the mercenary set :)
**Changelog**
:cl: cooldolphin
- add: The mercenary outfit is now available for equipping in the loadout menu.
> Mercenary set in general loadout

- Resources/Prototypes/_CP14/Entities/Clothing/Back/backpacks.yml
- Resources/Prototypes/_CP14/Entities/Clothing/Back/backpacks_satchels.yml
- Resources/Prototypes/_CP14/Entities/Clothing/Belt/pouch.yml
- Resources/Prototypes/_CP14/Entities/Clothing/Belt/quiver.yml
- Resources/Prototypes/_CP14/Entities/Mobs/NPC/animals.yml
- Resources/Prototypes/_CP14/Recipes/Workbench/LeatherWorking/tanner.yml
Добавляем медведю дроп шкуры.
Правим скорость между сатчелями и рюкзачками.
Добавляем крафт колчана и алхимического пояса
Всё должно быть хорошо. Понемногу вводим кожу в экономику.
Пока нету траты стамины - будут затраты в скорости.
**Changelog**
:cl:
- add: Adding a bear skin drop.
- add: Adding quiver and alchemy belt crafting
- tweak: Adjusting the speed between satchels and backpacks.
> Backpacks tweaks

- Content.Server/_CP14/Procedural/GenerationLayers/CP14Biome.cs
- Content.Server/_CP14/Procedural/GenerationLayers/CP14Ore.cs
- Content.Server/_CP14/Procedural/GenerationLayers/CP14Rooms.cs
:cl:
- fix: Fixed a bug where entities were duplicated during generation, which prevented digging ores in mines and chopping down trees.
> fix generation dublication

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/firewave.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_arrow.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_dagger.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_shards.yml
nerfed fire wave down to 2 damage (i think that was a previous value), ice arrow and ice dagger both have 5 second cooldown and cast times of 0.5 seconds ice dagger also has double the durability, ice shard now deals 6 cold (previously 4) and still has 2 pierce
firewave was too strong honestly took me too long to realize it and the other spells ive never seen used. outside of forced uses like raid skele ice shard
**Changelog**
:cl:
- tweak: Changed ice dagger now has its cooldown halved (5s now) and a cast time of 0.5 seconds, along with having 20 hits till breaking (4 for throwing).
- tweak: Changed ice arrow now has its cooldown halved (5s now) and a cast time of 0.5 seconds.
- tweak: Changed ice shard now does 6 cold and 2 pierce damage from 4 and 2.
- tweak: Changed fire wave now does …
> Spell rebalance

- Content.Shared/_CP14/Cooking/CP14SharedCookingSystem.cs
- Content.Shared/_CP14/Workbench/Requirements/FoodResource.cs
Подправлены цены при продаже супов на контрактах. Теперь за них не платят настолько много.
Теперь супы продаваемы по контрактам
fix #1620. 
:cl:
- fix: Now soups can be sold when completing contracts
- tweak: Now soups sell less when completing contracts
> Soup bugfix and price change

- Resources/Prototypes/Entities/Mobs/base.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Athletic/kick.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Athletic/sprint.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Demigods/Lumera/moon_strike.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Electric/lightning_strike.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Electric/lightning_strike_small.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Lurker/Kick.yml
- Resources/Prototypes/_CP14/Entities/fire.yml
fix #1634
fix #1575
fix #1612
:cl:
- tweak: Sprint buffs: Stamina consumption reduced by half. The less stamina you have, the slower you move, which is still the case, but sprinting is now useful again.
- fix: The web now ignites players upon contact if it is burning.
- fix: Spells that deal direct damage (kicks, lightning strikes, Lumera beams) now take into account the target's damage resistances.
> Bugfix portion

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Meta/mana_armor.yml
deleted the magic type from magic armor
no other metamagic spells have a magic type
> no more magic type mana armor

- Content.Client/Actions/UI/ActionAlertTooltip.cs
- Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
- Content.Shared/_CP14/MagicSpell/CP14SharedMagicSystem.Checks.cs
- Content.Shared/_CP14/MagicSpell/CP14SharedMagicSystem.Examine.cs
- Content.Shared/_CP14/MagicSpell/CP14SharedMagicSystem.cs
- Content.Shared/_CP14/MagicSpell/Components/CP14MagicEffectTargetMobStatusRequiredComponent.cs
- Content.Shared/_CP14/Skill/Effects/AddAction.cs
- Resources/Locale/en-US/_CP14/magicEnergy/magic-spells.ftl
- Resources/Locale/ru-RU/_CP14/magicEnergy/magic-spells.ftl
fix #1656
:cl:
- add: Spells now indicate if they have limited effects on certain creature types (e.g., healing only living creatures).
- add: The skill menu now displays detailed information about spells in advance, including restrictions.
> Spell pre-examine

- Resources/Prototypes/_CP14/Entities/Actions/Spells/Electric/speed_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/firewave.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/heat.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/hell_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Meta/mana_ballade.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/freeze.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_shards.yml
Iceshard now does 5 cold 2.5 pierce, fire wave nolonger adjusts the temp inside of someone and now has a cast time of 0.5 seconds (does not break on damage or move), all ballade spells now do not break on damage.
some of these spells are heavily under utilized and ice shard got a bit too big a buff and firewave one shots a skeleton if all connects due to the temp adjust.
**Changelog**
:cl:
- tweak: Changed Ice shard to now do 2.5 pierce and 5 cold total of 7.5 damage.
- tweak: Changed Fire wave to now have a 0.5 second cast time that cannot be interrupted and nolonger adjusts the temperature inside of someone.
- tweak: Changed magic, speed, and hell ballade spells to nolonger break upon being damaged.
- tweak: Changed Hell ballade now takes 8 mana per second and slows you down by 50% …
> More spell balance

- Resources/Prototypes/_CP14/Entities/Objects/Consumable/Drinks/goblet.yml
- Resources/Prototypes/_CP14/Entities/Objects/Weapons/Magic/twoHandedStaffs.yml
Added prices for two artefacts that did not have them previously.
Добавил цену для двух артефактов, которые её ранее не имели.
**Changelog**
:cl:
- add: Added price for artefacts bottomless goblet and magic healing staff.
> Price of artifacts

- Content.Client/_CP14/IdentityRecognition/CP14IdentityRecognitionBoundUserInterface.cs
- Content.IntegrationTests/Tests/EntityTest.cs
- Content.Server/_CP14/GameTicking/Rules/CP14VampireRuleSystem.cs
- Content.Server/_CP14/Objectives/Systems/CP14VampireObjectiveConditionsSystem.cs
- Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs
- Content.Server/_CP14/Vampire/CP14VampireSystem.Announce.cs
- Content.Server/_CP14/Vampire/CP14VampireSystem.cs
- Content.Shared/_CP14/IdentityRecognition/CP14SharedIdentityRecognitionSystem.cs
- Content.Shared/_CP14/MagicSpell/Spells/Vampire/CP14SpellPointerToVampireClan.cs
- Content.Shared/_CP14/MagicSpell/Spells/Vampire/CP14SpellTeleportToVampireSingleton.cs
- Content.Shared/_CP14/Trading/Systems/CP14SharedTradingPlatformSystem.cs
- Content.Shared/_CP14/Vampire/Components/CP14VampireClanHeartComponent.cs
- Resources/Locale/en-US/_CP14/identity/identity_recognition.ftl
- Resources/Locale/en-US/_CP14/objectives/condition/vampire.ftl
- Resources/Locale/en-US/_CP14/vampire/vampire.ftl
- Resources/Locale/ru-RU/_CP14/identity/identity_recognition.ftl
- Resources/Locale/ru-RU/_CP14/objectives/condition/vampire.ftl
- Resources/Locale/ru-RU/_CP14/vampire/vampire.ftl
- Resources/Prototypes/_CP14/Catalog/Fills/closets.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/air_saturation.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Meta/mana_splitting.yml
- Resources/Prototypes/_CP14/Entities/Actions/Spells/Vampire/search_vampire.yml
- Resources/Prototypes/_CP14/Entities/Mobs/Player/DemiplaneAntag/lurker.yml
- Resources/Prototypes/_CP14/Skill/Vampire/vampire.yml
:cl:
- add: Innkeepers now have starting seeds, hoes, and hatchets, while alchemists have roundstart sickles.
- fix: If you try to remember the name of a person wearing a mask, a warning will appear stating that you cannot remember the name of a person who is hiding their face.
- add: Admins can now also see vampire notifications about clan heart progression.
- remove: Lurkers can no longer pull items and mobs.
- fix: The teleport spell to the vampire glyph no longer has a random 1-tile shift, which caused people to get stuck in walls.
- tweak: The spell to search for enemy vampire clans is now T2 instead of T3, and also now points to enemy hearts.
- tweak: Changed the main goal of the vampire clan: Now the clan must upgrade its heart to level 3 and prevent other clans from doing so.
- …
> Balance tweaks

- Resources/Prototypes/_CP14/Entities/Mobs/NPC/rat.yml
The rat is too strong, weaken it to a more acceptable level. Now an armed adventurer will be able to handle one rat.
Крыса слишком сильная, ослабляет до более приемлемого уровня. Теперь вооруженный авантюрист сможет справится с одной крысой.
**Changelog**
:cl:
- tweak: Rat damage reduced by half. Duration of mob rat aggression reduced.
> Debaff rat

- Resources/Prototypes/_CP14/Entities/Markers/Spawners/mobs.yml
- Resources/Prototypes/_CP14/Entities/Mobs/NPC/zombie.yml
- Resources/Prototypes/_CP14/Entities/Mobs/Species/zombie.yml
- Resources/Prototypes/_CP14/Entities/Objects/Economy/wallet.yml
- Resources/Prototypes/_CP14/InventoryTemplates/partial_inventory_template.yml
- Resources/Prototypes/_CP14/Loadouts/Misc/undead_startinggear.yml
- Resources/Prototypes/_CP14/Species/zombie.yml
Fixed a very old bug: walking dead can now be female. Added a couple of new clothing options for the dead and some small loot. Made normal display of clothing slots for walking dead and mannequin.
Починил очень давнюю ошибку, ходячие мертвецы теперь могут быть и женского пола. Добавил пару новых вариантов одежды для мертвецов и небольшой лут. Сделал нормальное отображение слотов одежды у ходячих мертвецов и манекена.
A little more loot from the walking dead, for adventurers to earn money.
Чуть больше лута с ходячих мертвецов, для заработка авантюристам.
**Changelog**
:cl:
- add: Adds money to the wallets of some walking dead.
- tweak: Wallets can be cut into scraps of leather.
- fix: The walking dead can be women.
> Fixs zombie and loot

- Content.Shared/Actions/SharedActionsSystem.DoAfter.cs
- Resources/Prototypes/_CP14/Species/silva.yml
fix #1795
:cl:
- fix: Spells are interrupted again if players move far away from target or drop the item used for casting, or loses sight of the target
- fix: After an interrupted spell cast, the cooldown begins again, preventing spamming.
> Magic now respect physics again

- Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/vials.yml
the vials now start transfering at 5u, instead of 1u
**Changelog**
- tweak: The vials now start transfering at 5u, instead of 1u
> small alchemy QOL
