Content.Shared/CCVar/CCVars.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs

Вынес регулярное выражение для проверки имени в CCVar и добавил в него русские символы

Обновление регулярки для имени персонажа

---

Resources/Textures/_CP14/Structures/Furniture/chairs.rsi/meta.json

New upstream?

---

Resources/Prototypes/Entities/Objects/Misc/paper.yml
Resources/Prototypes/_CP14/Entities/Objects/Misc/CP14Paper.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/bonfire.yml
Resources/Prototypes/_CP14/tags.yml

Adding a whitelist for bonfire
In order to place only certain objects into the fire
https://github.com/crystallpunk-14/crystall-punk-14/assets/139079015/a02bca3d-c19f-4649-a1cd-050995d6f278
**Changelog**
:cl: Litogin
- add: Added whitelist for bonfire

Bonfire whitelist

---

Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/heater.yml

Whitelist for alchemy furnace
The same as in this PR: #137
**Changelog**
:cl: Litogin
- add: Added whitelist for alchemy furnace

Whitelist for alchemy furnace

---

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Content.Shared/Humanoid/HumanoidCharacterAppearance.cs
Content.Shared/Humanoid/SkinColor.cs
Content.Shared/_CP14/Humanoid/CP14SkinColor.cs
Resources/Prototypes/_CP14/Species/tiefling.yml

Limiting color choices for tiefligs.
resolves: #142
:cl:
- add: Added tiefling color selection restriction (1984).

New tiefling hue

---

Content.Shared/Decals/DecalPrototype.cs
Resources/Prototypes/Maps/debug.yml
Resources/Prototypes/_CP14/Decal/nature.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/herbals.yml
Resources/Prototypes/_CP14/Procedural/biomes_template_grasslands.yml

Dev map with new CP14Grassland biome
- new biome inheritance system
- bloodgrass spawning

Overworld biome overhaul

---

Resources/Locale/en-US/_CP14/reagents/meta/basic-effect-reagent.ftl
Resources/Locale/ru-RU/_CP14/reagents/meta/basic-effect-reagent.ftl
Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/herbals.yml
Resources/Prototypes/_CP14/Entities/Structures/Flora/floorWater.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/herbals.yml
Resources/Prototypes/_CP14/Reagents/basic-effects.yml
Resources/Prototypes/_CP14/Recipes/Reactions/biological.yml
Resources/Prototypes/_CP14/Recipes/Reactions/chromium_inverse.yml

- removed blunt, slash, piercing healing solutions, only general brute now
- rename rainbow to hallucinogenic solution
- add HideContextMenu tag to water and slime

alchemy mini fix

---

Content.Server/Chemistry/EntitySystems/SolutionHeaterSystem.cs
Content.Server/_CP14/Temperature/Fireplace/CP14FireplaceComponent.cs
Content.Server/_CP14/Temperature/Fireplace/CP14FireplaceSystem.cs
Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
Content.Shared/Storage/StorageComponent.cs
Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/tools.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/wallmount_torch.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/heater.yml
Resources/Prototypes/_CP14/Recipes/Reactions/biological.yml
Resources/Prototypes/_CP14/Recipes/Reactions/chromium_inverse.yml
Resources/Prototypes/_CP14/tags.yml

- fix alchemy furnace
- fix torches
- fix mortar and pestle

Ru Alchemy playtest bugfixes

---

Resources/Prototypes/_CP14/InventoryTemplates/human_inventory_template.yml

Belt slots now depending on pants

---

Content.Client/Weapons/Melee/MeleeWeaponSystem.Effects.cs

The sum of the length factors must not exceed 1
fixes #44

lung melee animation fix

---

Resources/Prototypes/Voice/disease_emotes.yml
Resources/Prototypes/Voice/speech_emotes.yml

Пофиксил нормально, без удалений, всё по ГОСТу
fixes #238 
no media, no fun

fixed ru emote sound v2

---

Content.Server/Chemistry/EntitySystems/SolutionHeaterSystem.cs
Content.Server/_CP14/Chemistry/ReagentEffect/CP14InverseEffect.cs
Content.Server/_CP14/Temperature/CP14FlammableSolutionHeaterComponent.cs
Content.Server/_CP14/Temperature/CP14SolutionTemperatureComponent.cs
Content.Server/_CP14/Temperature/CP14SolutionTemperatureSystem.cs
Resources/Locale/en-US/_CP14/guidebook/chemistry/effects.ftl
Resources/Locale/ru-RU/_CP14/guidebook/chemistry/effects.ftl
Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/tools.yml
Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/vials.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/normalizer.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/vat.yml
Resources/Prototypes/_CP14/Recipes/Reactions/Alchemy/chromium_inverse.yml

- solution heating refactor
- chromium slime reactions refactor into reaction effect

Alchemy fun mechanics

---

Resources/Prototypes/_CP14/Entities/Structures/Walls/walls.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Walls/WallStone.yml
Resources/Prototypes/_CP14/Recipes/Construction/walls.yml

I added craft for stone walls. 
Я добавил крафт для каменных стен. 
Players will be able to build their own houses and other buildings. 
Игроки смогут строить себе дома и другие здания. 
https://github.com/crystallpunk-14/crystall-punk-14/assets/155736295/1b8592d1-7e94-43ea-8b1d-082b4d440c36

Craft for stone walls.

---

Resources/Textures/Shaders/hcut.swsl

No Jesus dwarfs

---

Resources/Textures/_CP14/Tiles/Grass/attribution.yml
Resources/Textures/_CP14/Tiles/GrassLight/attribution.yml
Resources/Textures/_CP14/Tiles/GrassTall/attribution.yml
Resources/Textures/_CP14/Tiles/Water/water.rsi/meta.json
Resources/Textures/_CP14/Tiles/chasm.rsi/meta.json

- water floor
- grass tiles
- chasms

CC-BY-SA-3.0 for some assets

---

Resources/Prototypes/_CP14/Entities/Structures/Walls/iron_grille.yml

Fixes this issue https://github.com/crystallpunk-14/crystall-punk-14/issues/268
Tweak sound to metall sound collection. No code.
Smol change

fix CP14IronGrilleGate to chainy metall sound collection

---

Content.Client/Overlays/StencilOverlay.cs
Content.Client/_CP14/Overlays/StencilOverlay.WorldEdge.cs
Content.Server/_CP14/WorldEdge/CP14WorldEdgeSystem.cs
Content.Shared/_CP14/WorldEdge/CP14SharedWorldEdgeSystem.cs
Content.Shared/_CP14/WorldEdge/CP14WorldBoundingComponent.cs
Content.Shared/_CP14/WorldEdge/CP14WorldEdgeComponent.cs
Content.Shared/_CP14/WorldEdge/CP14WorldRemovePendingComponent.cs
Resources/Locale/en-US/_CP14/worldEdge/world-edge.ftl
Resources/Locale/ru-RU/_CP14/worldEdge/world-edge.ftl
Resources/Maps/_CP14/alchemy_test.yml

- add world borders (radius, like gateways worlds)

World borders

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

i love yourrrr tool, asqw

---

Resources/Locale/en-US/_CP14/species/species-names.ftl
Resources/Locale/ru-RU/_CP14/species/species-names.ftl
Resources/Prototypes/_CP14/Datasets/Names/species-names.yml
Resources/Prototypes/_CP14/Species/goblin.yml

removes 9 lines of code
Fix #310

Fix Goblin lastnames

---

Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
Content.Server/_CP14/Objectives/Components/CP14CurrencyCollectConditionComponent.cs
Content.Server/_CP14/Objectives/Systems/CP14CurrencyCollectConditionSystem.cs
Content.Shared/_CP14/Currency/CP14CurrencyComponent.cs
Content.Shared/_CP14/Currency/CP14CurrencySystem.cs
Resources/Locale/en-US/_CP14/currency/currency_comp.ftl
Resources/Locale/en-US/_CP14/objectives/condition/expedition.ftl
Resources/Locale/en-US/_CP14/objectives/condition/issuers.ftl
Resources/Locale/en-US/_CP14/objectives/condition/personal.ftl
Resources/Locale/ru-RU/_CP14/currency/currency_comp.ftl
Resources/Locale/ru-RU/_CP14/objectives/condition/issuers.ftl
Resources/Locale/ru-RU/_CP14/objectives/condition/personal.ftl
Resources/Maps/_CP14/battle_royale.yml
Resources/Prototypes/_CP14/Entities/Objects/Economy/coins.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/battleHammer.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/battleStaff.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/dagger.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/handheldAxe.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/lightHammer.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/mace.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/sickle.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/sword.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Melee/twoHandedSword.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Ranged/lightCrossbow.yml
Resources/Prototypes/_CP14/GameRules/roundstart.yml
Resources/Prototypes/_CP14/Objectives/personal_objectives.yml

Currency collect goal

---

Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Furniture/mannequin.yml

Items will not be destroyed on the Menequin after disassembly.
https://github.com/space-wizards/space-station-14/pull/30313

Fix Mannequin

---

Content.Server/_CP14/GameTicking/Rules/CP14ExpeditionObjectivesRule.cs
Content.Server/_CP14/GameTicking/Rules/Components/CP14ExpeditionObjectivesRuleComponent.cs
Resources/Maps/_CP14/alchemy_test.yml
Resources/Maps/_CP14/battle_royale.yml
Resources/Maps/_CP14/meteor-arena.yml
Resources/Prototypes/_CP14/Entities/Markers/Spawners/jobs.yml
Resources/Prototypes/_CP14/GameRules/roundstart.yml
Resources/Prototypes/_CP14/Maps/arenas.yml
Resources/Prototypes/_CP14/Objectives/expedition_objectives.yml
Resources/Prototypes/_CP14/Objectives/personal_objectives.yml

- different objectives for different roles
- support of randomization goals via weightrandomgroup
- department goals

Crew goals update

---

Resources/Textures/_CP14/Shaders/wave.swsl

Fix wave compability with GLES

---

Content.Client/Overlays/StencilOverlay.cs
Content.Client/_CP14/Overlays/StencilOverlay.CloudShadows.cs
Content.Server/_CP14/DayCycle/CP14CloudShadowsSystem.cs
Content.Server/_CP14/DayCycle/CP14DayCycleSystem.cs
Content.Server/_CP14/DayCycle/Commands/CP14AddTimeEntryCommand.cs
Content.Server/_CP14/DayCycle/Commands/CP14InitDayCycleCommand.cs
Content.Server/_CP14/DayCycle/Commands/CP14SetTimeEntryCommand.cs
Content.Server/_CP14/Farming/CP14FarmingSystem.cs
Content.Shared/_CP14/DayCycle/CP14DayCyclePeriodPrototype.cs
Content.Shared/_CP14/DayCycle/CP14SharedDayCycleSystem.cs
Content.Shared/_CP14/DayCycle/Components/CP14CloudShadowsComponent.cs
Content.Shared/_CP14/DayCycle/Components/CP14DayCycleComponent.cs
Content.Shared/_CP14/Random/Rules/IsDaylight.cs
Resources/Maps/_CP14/alchemy_test.yml
Resources/Maps/_CP14/battle_royale.yml
Resources/Maps/_CP14/dev_map.yml
Resources/Maps/_CP14/template.yml
Resources/Prototypes/_CP14/DayCycle/periods.yml

System cleanup, migration, etc. From the important, now there are different prototypes for time periods, now there is no ugly boolean variable `IsNight`.

Remove day cycle shit

---

Resources/Prototypes/_CP14/Entities/Structures/Floor/floorWater.yml

Вода теперь тушит.
Прототип воды перенес в папку floor
fix #377

Вода теперь не в папке флоры, а в папке Floor. Вода теперь тушит.

---

Content.Client/_CP14/WorldSprite/CP14WorldSpriteComponent.cs
Content.Client/_CP14/WorldSprite/CP14WorldSpriteSystem.cs
Content.Server/Entry/IgnoredComponents.cs
Content.Shared/_CP14/WorldSprite/WorldSpriteVisualLayer.cs
Resources/Prototypes/_CP14/debug.yml

> [!CAUTION]
> SHITY COOOOOOODE
Make some tweaks on client side to give ability separate world sprites and others
It's cool

Added world sprite system

---

Content.Client/_CP14/Wave/CP14WaveShaderSystem.cs
Content.Shared/_CP14/Configuration/CP14ConfigVars.cs

Добавил конфигурацию для CP14, а так же её значение для шейдера покачивания что бы его отключать
Лагает на слабых девайсах, робуст ишью

Added configuration for wave shader

---

Content.Shared/_CP14/MagicSpell/CP14SharedMagicSystem.cs
Content.Shared/_CP14/MagicSpell/Events/CP14DelayedActionEvents.cs
Content.Shared/_CP14/MagicSpell/Events/CP14IDelayedMagicEffect.cs
Content.Shared/_CP14/MagicSpell/Spells/CP14SpellProjectile.cs
Resources/Prototypes/_CP14/Entities/Actions/Spells/cure_wounds.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/earth_wall.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/fireball.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/flash_light.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/ice_floor.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/ice_shards.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/shadow_grab.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/shadow_step.yml

move all magic events to EntityWorldTargetEvent
now Projectile events prioritize entity nether click coords

Magic update

---

Resources/Prototypes/_CP14/Entities/Objects/Economy/wallet.yml

Заменил звук у кошеля с мешка для мусора на сумку
Звук не вписывается в антураж

Звук кошеля

---

Resources/Prototypes/_CP14/Body/Parts/zombie.yml
Resources/Prototypes/_CP14/Body/Prototypes/zombie.yml
Resources/Prototypes/_CP14/Entities/Mobs/Species/zombie.yml

Zombie speed fix, now they are slower and a little less survivable. Also, added all the body parts for the zombies.
Фикс скорости зомби, теперь они медленнее и немного менее живучие. Также, добавил все части тел для зомби.

Fix Zombie

---

Resources/Prototypes/_CP14/Entities/Mobs/NPC/undead.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/xeno_test.yml
Resources/Prototypes/_CP14/Entities/Mobs/Species/base.yml
Resources/Prototypes/_CP14/ai_factions.yml

Creates separate factions for this build, in which the relationship between mobs and players can already be regulated.
Создаёт отдельные фракции для этой сборки, в которой уже можно будет регулировать отношения между мобами и игроками.
Soon there will be a greater number of mobs, and the relationship between them already need to be built on the basis of the need for this build, not vanilla, where the relationship is completely different.
Вскоре появится большее количество мобов, и отношения между ними уже нужно строить из расчета необходимости этой сборки, а не ванильной, где совсем иные взаимоотношения.

AI Factions

---

Content.Shared/_CP14/MagicSpellStorage/CP14SpellStorageSystem.cs

Fixed https://github.com/crystallpunk-14/crystall-punk-14/issues/462

Fix #462 (Attuning magic items problem)

---

Content.Client/Overlays/StencilOverlay.cs
Content.Client/_CP14/Localization/CP14LocalizationVisualsComponent.cs
Content.Client/_CP14/Localization/CP14LocalizationVisualsSystem.cs
Resources/Prototypes/_CP14/Catalog/Fills/closets.yml
Resources/Prototypes/_CP14/Recipes/Workbench/workbench.yml

- fix cloud overlay layering
- add syringe into alchemist closet
- added localization visuals.

Clouds overlay fix + Syringe + Localization visuals

---

Resources/Prototypes/_CP14/Entities/Mobs/NPC/dinosaurs.yml
Resources/Prototypes/_CP14/Entities/Mobs/Species/zombie.yml

Now the zombies and dinosaurs are definitely climbing on the table
Теперь зомби и динозавры точно лезут на стол

Zombies climbing in and other things

---

Content.Server/_CP14/GameTicking/Rules/CP14CommonObjectivesRule.cs
Content.Server/_CP14/GameTicking/Rules/CP14PersonalObjectivesRule.cs
Content.Server/_CP14/GameTicking/Rules/Components/CP14CommonObjectivesRuleComponent.cs
Content.Server/_CP14/GameTicking/Rules/Components/CP14PersonalObjectivesRuleComponent.cs
Content.Server/_CP14/Objectives/Components/CP14TownSendConditionComponent.cs
Content.Server/_CP14/Objectives/Systems/CP14CurrencyCollectConditionSystem.cs
Content.Server/_CP14/Objectives/Systems/CP14TownSendConditionSystem.cs
Content.Server/_CP14/StealArea/CP14StealAreaAutoJobConnectComponent.cs
Content.Server/_CP14/StealArea/CP14StealAreaAutoJobConnectSystem.cs
Content.Shared/Mind/SharedMindSystem.cs
Resources/Locale/en-US/_CP14/currency/currency_comp.ftl
Resources/Locale/en-US/_CP14/objectives/condition/empire-order.ftl
Resources/Locale/en-US/_CP14/objectives/condition/personal.ftl
Resources/Locale/en-US/_CP14/objectives/end-text.ftl
Resources/Locale/en-US/_CP14/objectives/steal-targets.ftl
Resources/Locale/ru-RU/_CP14/objectives/condition/empire-order.ftl
Resources/Locale/ru-RU/_CP14/objectives/condition/personal.ftl
Resources/Locale/ru-RU/_CP14/objectives/end-text.ftl
Resources/Locale/ru-RU/_CP14/objectives/steal-targets.ftl
Resources/Prototypes/_CP14/Entities/Mobs/NPC/animals.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/dinosaurs.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/monster.yml
Resources/Prototypes/_CP14/Entities/Objects/ores.yml
Resources/Prototypes/_CP14/Objectives/empire_orders.yml
Resources/Prototypes/_CP14/Objectives/personal_objectives.yml
Resources/Prototypes/_CP14/Objectives/steal_target_groups.yml

- added parsing of personal and common objectives to round end message:
- removed gold ore collection objective
- add monster corpse collect objective

Endscreen message + command objectives updadte

---

Resources/Prototypes/_CP14/Entities/Mobs/NPC/animals.yml

Now you can pet pigs and she can go to rest with a free soul. Boars can be stroked too, but it's more complicated.
Теперь можно гладить свиней, и она сможет пойти на упокой со свободной душой. Кабанов тоже можно гладить, но сложнее.
Everyone needs to be petted, and no one leaves without being petted.
Всех нужно погладить, и никто не уйдет непогладив.

Petting pigs

---

Resources/Prototypes/_CP14/Entities/Structures/Furniture/barrel.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Furniture/Misc.yml
Resources/Prototypes/_CP14/Recipes/Construction/furniture.yml
Resources/Prototypes/_CP14/Recipes/Workbench/workbench.yml

Крафт бочки перенесён из верстака на панель строительства с помощью кнопки `G` / `П`
Fix #475
https://github.com/user-attachments/assets/8f3fe120-2ea3-4286-8340-0f3dd367d96b

Delete structures on workbench

---

Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t1_caves_ring.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t1_grassland_island_ring.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/test.yml

New demiplan location, MORE ZOMBIES

---

Resources/Locale/en-US/_CP14/reagents/meta/basic-effect-reagent.ftl
Resources/Locale/ru-RU/_CP14/reagents/meta/basic-effect-reagent.ftl
Resources/Prototypes/_CP14/Reagents/Biological/biological.yml
Resources/Prototypes/_CP14/Reagents/Biological/flowers.yml
Resources/Prototypes/_CP14/Reagents/basic-effects.yml
Resources/Prototypes/_CP14/Recipes/Reactions/Alchemy/bloodflower.yml
Resources/Prototypes/_CP14/Recipes/Reactions/Alchemy/chromium_slime.yml
Resources/Prototypes/_CP14/Recipes/Reactions/Alchemy/dayflin.yml

- Blood flower sap now gives a blood restoring solution (used to be saturation)
- Dayflines sap are now useful! acceleration solutions
- Chromium slime can turn this into solutions to absorb blood solution and slowing solution

Alchemy blood restoring and accseleration solutions

---

Content.Shared/_CP14/Wallmount/CP14WallmountComponent.cs
Content.Shared/_CP14/Wallmount/CP14WallmountSystem.cs
Content.Shared/_CP14/Wallmount/CP14WallmountedComponent.cs

fix wallmount

---

Content.Server/_CP14/Demiplane/CP14DemiplanSystem.Generation.cs
Content.Server/_CP14/DemiplaneAdmin/CP14DemiplaneAdminSystem.cs
Content.Server/_CP14/DemiplaneAdmin/CP14DemiplaneRiftCatcherComponent.cs

Admins now can create custom demiplanes and catch players that enter in random demiplanes

admin demiplanes catcher

---

Content.IntegrationTests/Tests/EntityTest.cs
Content.Server/Procedural/DungeonSystem.Rooms.cs
Content.Server/_CP14/Demiplane/CP14DemiplanSystem.Connections.cs
Content.Server/_CP14/Demiplane/CP14DemiplanSystem.Generation.cs
Content.Server/_CP14/Demiplane/CP14DemiplaneSystem.cs
Content.Server/_CP14/DemiplaneTraveling/CP14DemiplaneTravelingSystem.cs

nothing interesting for players

Minor procedural fixes pack

---

Resources/Prototypes/_CP14/Entities/Structures/Flora/Crystal/elemental.yml
Resources/Prototypes/_CP14/Entities/Structures/Flora/Crystal/shards.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Reward/crystals.yml
Resources/Prototypes/_CP14/Recipes/Workbench/furnace.yml
Resources/migration.yml

All dangerous glowing quartz move to T2+
Normal not-glowing quartz returned to T1

Normal quartz returns

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
Tools/_CP14/LocalizationHelper/last_launch_result/result.json

translate all new entities to ru language

Ru localization sync

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
Resources/Prototypes/_CP14/Entities/Clothing/Head/Roles/guard.yml
Resources/Prototypes/_CP14/Entities/Structures/Flora/Crystal/shards.yml

Исправил несколько мелких ошибок из ишуев:
https://github.com/crystallpunk-14/crystall-punk-14/issues/845
https://github.com/crystallpunk-14/crystall-punk-14/issues/825
И исправил мелкую ошибку в локализации.

Small Fixes

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

Translation and revision of translation
Перевод и правка перевода

Перевод RU

---

Content.Server/_CP14/Cargo/CP14CargoSystem.cs
Content.Shared/_CP14/Cargo/Prototype/CP14StoreBuyPositionPrototype.cs
Content.Shared/_CP14/Cargo/Prototype/CP14StoreSellPositionPrototype.cs
Resources/Prototypes/_CP14/Catalog/Cargo/Store/Sell/metalls.yml
Resources/Prototypes/_CP14/Catalog/Cargo/Store/Sell/misc.yml
Resources/Prototypes/_CP14/Catalog/Cargo/Store/buy.yml
Resources/Prototypes/_CP14/Catalog/Cargo/Store/sell_special.yml

no more price randomization. QoL for boring merchants

Unrandomize store prices

---

Resources/Prototypes/_CP14/Entities/Mobs/Species/zombie.yml

Fix zombies not affected by stun

---

Resources/Prototypes/_CP14/Reagents/Biological/animal_origin.yml

Now the poison exists.
Теперь яд существует.
Fixing the constant yawning with no effect.
Починка постоянной зевоты без эффекта.

Fixing the whistleblower's poison

---

Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Tip/arrows.yml

Добавил "arrow" в названия наконечников стрел
issue https://github.com/crystallpunk-14/crystall-punk-14/issues/957

Added 'arrow' to the names of the arrowheads

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

Мелкий фикс перевода

---

Resources/Prototypes/_CP14/Entities/Clothing/Belt/quiver.yml
Resources/Prototypes/_CP14/Entities/Clothing/Rings/ring.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/skeleton.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/arrow.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/sword.yml
Resources/Prototypes/_CP14/Loadouts/Misc/undead_startinggear.yml

Добавлены вариации скелетам из демиплана
Мечник
- вместо костяной алебарды имеет костяной меч
- на голову одет железный обруч
Ловкач
- В качестве оружия имеет 2 железных кинжала
- Носит маску грешника и не имеет обуви
Лучник
- Имеет лук и колчан с медными стрелами(также добавлены в этом ПРе)
- Заместо факела, в кармане лежит свиток создания сфер света т.к. факел не позволит стрелять из лука
Волшебник
- Имеет обычную одежду: черная рубашка, коричневые штаны, остроконечная шляпа, плащ
- Имеет уникальное магическое кольцо которое нельзя снять и на которое надо настроиться(поскольку без компонента настройки заклинания не появляются на предметах, надетых изначально)
- Заклинания: Ледяные осколки, Сфера света, Лечение ран, Создание пламени
Игра на скелетах несколько однообразна и они больше не …

Обновление скелетов

---

Content.Client/_CP14/Knowledge/ClientCP14KnowledgeSystem.cs
Content.Server/_CP14/Knowledge/CP14KnowledgeAdminUtilitiesSystem.cs
Content.Server/_CP14/Knowledge/CP14KnowledgeSystem.cs
Content.Server/_CP14/Knowledge/Specials/CP14AddKnowledgeSpecial.cs
Content.Shared/_CP14/Knowledge/CP14KnowledgePaperTextSystem.cs
Content.Shared/_CP14/Knowledge/Components/CP14AllKnowingComponent.cs
Content.Shared/_CP14/Knowledge/Components/CP14AutoAddKnowledgeComponent.cs
Content.Shared/_CP14/Knowledge/Components/CP14KnowledgeLearningSourceComponent.cs
Content.Shared/_CP14/Knowledge/Components/CP14KnowledgePaperTextComponent.cs
Content.Shared/_CP14/Knowledge/Components/CP14KnowledgeStorageComponent.cs
Content.Shared/_CP14/Knowledge/Events/CP14KnowledgeInfoEvent.cs
Content.Shared/_CP14/Knowledge/Events/CP14KnowledgeLearnDoAfterEvent.cs
Content.Shared/_CP14/Knowledge/Events/CP14KnowledgeUsedEvent.cs
Content.Shared/_CP14/Knowledge/Events/CP14RequestKnowledgeInfoEvent.cs
Content.Shared/_CP14/Knowledge/Prototypes/CP14KnowledgePrototype.cs
Content.Shared/_CP14/Knowledge/SharedCP14KnowledgeSystem.cs
Content.Shared/_CP14/Workbench/Requirements/KnowledgeRequired.cs
Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Resources/Prototypes/_CP14/Entities/Objects/Bureaucracy/Books/knowledge.yml

Code cleanup, the first part of the changes concerning the knowledge system,
which cleans up the old system
Readability

Knowledge refactor

---

Content.Shared/_CP14/MagicManacostModify/CP14MagicManacostModifySystem.cs

Changed magic-global display

---

Resources/Prototypes/_CP14/Catalog/Cargo/Store/General/sell_special.yml
Resources/Prototypes/_CP14/Catalog/Cargo/Store/Sylphoria/sell_special.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Economy/trade_portal.yml

Add spell scrolls special sell positions
Add cooked buns universal special sell position
Increase pie price

Minor Trading expance

---

Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/T0_heal_ballade.yml

Немного бафнул лечение от балады. Теперь оно более внушительное. 
A little buff treatment for balada. It's more impressive now.

 Heal Ballade Buff

---

Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/cleaner.yml

Update cleaner.yml 

---

Resources/Prototypes/_CP14/Recipes/Workbench/Anvil/modular_breastplate.yml

Медная броня из меди, золото из золота.

Fix armour

---

Resources/Prototypes/_CP14/Entities/Mobs/NPC/skeleton.yml

Fix [issue](https://github.com/crystallpunk-14/crystall-punk-14/issues/996)

Fix halberd skeleton

---

Content.Shared/_CP14/MagicManacostModify/CP14MagicManacostModifySystem.cs
Resources/Locale/en-US/_CP14/magicEnergy/magic-clothing.ftl
Resources/Locale/ru-RU/_CP14/magicEnergy/magic-clothing.ftl
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/test_armor.yml

Fix [issue](https://github.com/crystallpunk-14/crystall-punk-14/issues/958)

Separated mana modifiers 

---

Content.Client/IconSmoothing/IconSmoothComponent.cs
Content.Client/IconSmoothing/IconSmoothSystem.cs
Resources/Prototypes/_CP14/Entities/Structures/Floor/floorLava.yml
Resources/Prototypes/_CP14/Entities/Structures/Floor/floorWater.yml
Resources/Prototypes/_CP14/Entities/Structures/Walls/walls.yml
Resources/Prototypes/_CP14/Entities/Structures/chasm.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Structures/Walls/WallWood.yml
Resources/Prototypes/_CP14/Recipes/Construction/walls.yml

copy of https://github.com/space-wizards/space-station-14/pull/35790
Wooden palisade are now integrated into the game and can be built by players
Water, lava and chasms are now glued to walls
Частокол теперь интегрирован в игру и может строится игроками
Вода, лава и бездны теперь склеиваются с стенами

Palisade integration + IconSmooth improvement

---

Resources/Prototypes/_CP14/Entities/Objects/Consumable/Food/produce.yml

Onions and peppers can be put in a sack.
Лук и перец можно положить в мешок.
Fix #1014

Fix tag food

---

Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.cs
Content.Server/_CP14/UniqueLoot/CP14UniqueLootSystem.cs
Content.Shared/Localizations/ContentLocalizationManager.cs
Resources/ConfigPresets/_CP14/Dev.toml

Back to ru CBT

---

Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs
Content.Server/_CP14/UniqueLoot/CP14UniqueLootSystem.cs
Content.Shared/Localizations/ContentLocalizationManager.cs
Resources/ConfigPresets/_CP14/Dev.toml
Resources/Prototypes/_CP14/Entities/Structures/Storage/Crates/coffin.yml
Resources/Prototypes/_CP14/ModularCraft/Blade/dagger.yml
Resources/Prototypes/_CP14/ModularCraft/Blade/sickle.yml
Resources/Prototypes/_CP14/Roles/Antags/vampire.yml

English OBT + Bugfixes

---

Resources/Prototypes/_CP14/Entities/Clothing/Masks/masks.yml

```CP14ClothingMaskBoneMaskMind``` перенесена в ```HideSpawnMenu```
``CP14ClothingMaskBoneMaskMind`` moved to ``HideSpawnMenu``.
#1041

[Fix]Bone mask fix

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

Фикс названия бочки с кварцом...почему-то кварц был грубым...

[Fix][Ru] Fix BarrelGroundQuartz locale 

---

Resources/ConfigPresets/_CP14/Dev.toml
Resources/Locale/en-US/_CP14/ghostRoles/roles.ftl
Resources/Locale/ru-RU/_CP14/ghostRoles/roles.ftl
Resources/Maps/_CP14/comoss.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/Slimes/base.yml
Resources/Prototypes/_CP14/Entities/Mobs/NPC/skeleton.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t1_grassland_island.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t2_grass_geode.yml

Back to Ru CBT + Bugfixes

---

Resources/Prototypes/_CP14/Catalog/Cargo/Store/Sylphoria/sell.yml
Resources/Prototypes/_CP14/Catalog/Cargo/Store/Sylphoria/sell_special.yml

Удалил амулет из торгов. Поправил количество люцены в продаже.

Deleted trade amulet

---

Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Breastplate/chainmail.yml

Кольчуга в руках теперь будет менять цвет согласно своему материалу.

Coloured chainmail

---

Resources/Prototypes/_CP14/Entities/Objects/Bureaucracy/paper.yml

Изменен цвет бумаги.
Change paper color.
Слишком чистая бумага была.
Paper was too clean.

[Fix]Paper color fix

---

Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Breastplate/chainmail.yml
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Breastplate/cuirass.yml
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Breastplate/infantry_cuirass.yml
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Cuisses/chainmail.yml
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Cuisses/plate.yml
Resources/Prototypes/_CP14/Entities/Clothing/OuterClothing/ModularArmor/Alchemist/Greave/chainmail.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/axe.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/dagger.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/hammer.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/mace.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/pickaxe.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/rapier.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/shovel.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/sickle.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/spear.yml
Resources/Prototypes/_CP14/Entities/Objects/ModularTools/Alchemist/Blade/sword.yml

АНГЛ ЛОКАЛЬ

---

Resources/Prototypes/_CP14/Catalog/Cargo/Store/BradFamily/buy.yml
Resources/Prototypes/_CP14/Entities/Objects/Materials/simple.yml
Resources/Prototypes/_CP14/Entities/Objects/Specific/Medical/healing.yml

Фиксит марлю, снова можно лечиться. Зелье лечения истощения маны есть в торговом шкафу.

Fix bandage

---

Resources/Locale/en-US/_CP14/loadouts/loadout.ftl
Resources/Locale/ru-RU/_CP14/loadouts/loadout.ftl
Resources/Prototypes/_CP14/Loadouts/Jobs/guildmaster.yml
Resources/Prototypes/_CP14/Loadouts/role_loadouts.yml
Resources/Prototypes/_CP14/Roles/Jobs/Mercenary/guildmaster.yml

Рапира гильдмастера не выдавалась в раунде. Исправлено. 
The guildmaster's rapier was not given out in the round. Fixed.

The guildmaster's rapier was not given out in the round. 

---

Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Furniture/cabinets.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Furniture/closets.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Furniture/curtains.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Structures/Doors/grilles.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Structures/Doors/iron_doors.yml
Resources/Prototypes/_CP14/Recipes/Construction/Graphs/Structures/Doors/wooden_doors.yml

Чинит рецепты крафта конструкций
Fixes #1097, Fixes #1098

fix constructions

---

Content.Server/_CP14/WeatherEffect/CP14WeatherEffectJob.cs
Content.Shared/Weather/WeatherPrototype.cs
Content.Shared/_CP14/WeatherEffect/CP14WeatherRefillableComponent.cs
Content.Shared/_CP14/WeatherEffect/Effects/ApplyEntityEffect.cs
Content.Shared/_CP14/WeatherEffect/Effects/CP14WeatherEffect.cs
Content.Shared/_CP14/WeatherEffect/Effects/RefillSolutions.cs
Content.Shared/_CP14/WeatherEffect/Effects/SpawnEntityOnTop.cs
Resources/Prototypes/_CP14/Entities/Objects/Tools/bucket.yml
Resources/Prototypes/_CP14/Entities/Structures/Flora/Gatherable/base.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/barrel.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/vat.yml
Resources/Prototypes/_CP14/weather.yml

rain and storm now can refill buckets, barrels and vats

Weather refill

---

Content.Shared/Localizations/ContentLocalizationManager.cs
Resources/ConfigPresets/_CP14/Dev.toml

English OBT setup

---

Content.Server/_CP14/WeatherEffect/CP14WeatherEffectJob.cs
Resources/Locale/en-US/_CP14/demiplane/locations.ftl
Resources/Locale/ru-RU/_CP14/demiplane/locations.ftl
Resources/Prototypes/_CP14/Entities/Markers/Spawners/Random/Biome/biomeSpawner.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t1_wastelands.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/t2_magma_caves.yml
Resources/Prototypes/_CP14/Procedural/fill.yml
Resources/Prototypes/_CP14/Procedural/wastelands.yml

Wastelands

---

Resources/Prototypes/_CP14/Entities/Clothing/Eyes/eyes.yml

Всем очкам и моноклям добавлен компонент коррекции зрения
У нас есть черта которая ухудшает зрения но очки лучше не делают. Теперь делают

VisionCorrectorGlasses

---

Resources/Prototypes/_CP14/Species/tiefling.yml

Fix master

---

Content.Server/_CP14/DemiplaneTraveling/CP14StationDemiplaneMapSystem.cs
Resources/Prototypes/_CP14/Entities/Mobs/Player/DemiplaneAntag/Skeletons/T2.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Danger/mobs.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/GhostRoleDanger/misc.yml

исправлены гостроли демипланов
fixed demiplane ghostroles

emiplane ghostrole fix

---

Content.Server/_CP14/Workbench/CP14WorkbenchComponent.cs

Increase Workbench action radius
Увеличиваем радиус взаимодействия с WorkBench
Im lazy
Убираем дроч с тасканием по одной штучке продуктов на верстак.

Increase Workbench Radius

---

Resources/Prototypes/_CP14/Entities/Structures/Flora/Gatherable/Farm/wheat.yml
Resources/Prototypes/_CP14/Recipes/Workbench/CookingTable/misc.yml

Я поиграл за фермера и посчитал что текущие цифры не совсем честные, с учетом того сколько обычно готовится полный хлеб и сколько на него тратится пшеницы и времени.
Повышаем число собираемой пшеницы за урожай.
I played as a farmer and thought that the current figures are not quite fair, considering how long it usually takes to make a full loaf and how much wheat and time it takes.
We are increasing the amount of wheat collected per harvest.
поразмышлял над пшеницей и о том как я его пек, сколько тратил времени - и подумал что добычу пшена вполне можно повысить, а то не логично что 2 тайла пшеницы нужно чтобы испечь 1 булку хлеба которая накормит 1 человечка
цифры подменил чтобы 2 тайла могли накормить 1.5 человечка
Целого хумана и дварфа
ну или двух эльфов
ну или трех гоблинов.
I thought …

Wheat gather increase

---

Content.Server/_CP14/RoundLeave/CP14RoundLeaveSystem.cs
Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/cure_poison.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/Light/search_of_life.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/water_creation.yml
Resources/Prototypes/_CP14/Entities/Objects/Misc/bell.yml
Resources/Prototypes/_CP14/Entities/Structures/Decorations/flags_wallmount.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Demiplanes/round_end.yml
Resources/ServerInfo/_CP14/Guidebook_EN/JobsTabs/AdventurersTabs/Demiplanes.xml

Edited some (English) description text where formatting, phrasing seemed off, or information seemed to be lacking. Some of the tapestries had commas where the majority did not, so they were changed for equivalence.
Improve grammar and consistency
N/A, see changed files

Proofreading changes [EN]

---

Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs

Daily English CBT

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

Edit the Russian translation.
Правка перевода на русский.

Правка перевода RU

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl

fix raid skele desc

---

Resources/Locale/en-US/_CP14/loadouts/loadout.ftl

Corrected an English spelling mistake in the adventurer loadout menu.
Corrects a spelling mistake.

Fix a spelling mistake

---

Content.Server/_CP14/MagicEnergy/CP14MagicEnergySystem.cs
Resources/Prototypes/Reagents/Consumable/Food/food.yml
Resources/Prototypes/_CP14/Entities/Objects/Specific/Alchemy/vial_bomb.yml
Resources/Prototypes/_CP14/Trading/brad_potions.yml

- Исправлен экспойт с бесконечными деньгами через свитки. Пришлось откатывать возможность продавать магическую энергию.
- Сильно понерфлены цены на еду. 
---
- Fixed an exploit with infinite money through scrolls. Had to roll back the ability to sell magical energy.
- Food prices have been significantly nerfed.

Merchant: fix infinity moneys

---

Resources/Prototypes/_CP14/ModularCraft/Blade/pickaxe.yml

just cant put gardes on pickaxes anymore
I mean its obviously not intended based on the sprite.
i hate this thing with a burning passion

No more gardes on pickaxes

---

Resources/Prototypes/_CP14/Entities/fire.yml

**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

Ed 02 06 2025 changelog test 3

---

Resources/Changelog/CP14_Changelog.yml
Resources/Prototypes/_CP14/Entities/fire.yml

**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

Ed 02 06 2025 changelog test 4

---

Resources/Prototypes/_CP14/Entities/Objects/Bureaucracy/Books/books.yml

Fix guild moral proto
fix #1336 
**Changelog**
:cl: ArZarLordOfMango
- fix: Fixed Guild moral book

[Fix] Guild moral

---

Resources/Prototypes/Body/Parts/human.yml
Resources/Prototypes/_CP14/Entities/Clothing/Shoes/shoes.yml
Resources/Prototypes/_CP14/Entities/Objects/Keys/tools.yml
Resources/Prototypes/_CP14/Entities/Objects/Misc/crayons.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/Ranged/bow.yml

Добавил цены артефактам + пофиксил продажу костей с кладбища
**Changelog**
:cl:
- add: Now artifacts have a fair price!
- fix: Selling bones from the graveyard no longer yields platinum at the start of the game!

some price change

---

Resources/Prototypes/_CP14/Catalog/Fills/crates.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/pickaxe.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/rapier.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/skimitar.yml
Resources/Prototypes/_CP14/Entities/Objects/Weapons/ModularPresets/sword.yml
Resources/Prototypes/_CP14/Loadouts/Jobs/adventure.yml
Resources/Prototypes/_CP14/Loadouts/Jobs/general.yml

**Changelog**
:cl:
- tweak: Iron weapons and pickaxe in loadouts are now copper. 
- tweak: Iron pickaxes in boxes around the map now spawn much less often, but copper ones have appeared.

Copper time!

---

Content.Client/_CP14/UserInterface/Systems/NodeTree/CP14NodeTreeGraphControl.xaml.cs

Now in skill menu we can use mouse wheel to change scale. And use right click to reset it.

feat: skill ui scale

---

Content.Server/_CP14/Trading/CP14PriceScannerSystem.cs
Content.Shared/_CP14/WeatherEffect/Effects/RefillSolutions.cs
Resources/Prototypes/_CP14/Entities/Structures/Specific/Alchemy/heater.yml

**Changelog**
:cl:
- fix: Corpses and living creatures are no longer shown to be worth money (as they cannot be sold)
- fix: Rain no longer fills closed barrels and bottles with water
- fix: The furnace can now be rotated through the verb menu

Mini fix pack

---

Resources/Prototypes/_CP14/Entities/Objects/Tools/flashlight.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/wallmount_lamp.yml

All handheld crystal lamps now break upon sustaining 20 damage. They break upon smashing something with them three times, dropping a random portion of their craft materials.
Wall lanterns were already breakable, but now also drop a portion of their craft materials.
Edit: ~~WIP while I make lanterns less susceptible to fireballs~~ They will survive one direct fireball, but not two.
Все ручные хрустальные лампы теперь ломаются при получении 20 единиц урона. Они ломаются, если разбить ими что-нибудь три раза, возвращая случайную часть ремесленных материалов.
Настенные фонари и так уже ломались, а теперь еще и возвращают часть своих ремесленных материалов.
I keep seeing people talking about how lanterns are better one handed weapons than hammers and maces. That's stupid, a delicate magitech …

Lanterns Can Break

---

Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs

CBT 29.06 exception

---

Resources/Prototypes/_CP14/Reagents/target_effects.yml
Resources/Prototypes/_CP14/Recipes/Reactions/Thaumaturgy/Precursor/chromium_slime.yml

Made warming and soothing and ice solution adjust temperature reduced bloodhealing/absorption's health adjustment.
Warming solution didn't warm people also gives these solutions more utility outside of just healing their respective damage. Blood-absorption being the best damaging solution didn't make sense so its damage has been lightly nerfed.
**Changelog**
:cl:
- tweak: Changed warming solution to now actually warm people. Soothing now cools, and ice now freezes people.
- tweak: Changed blood healing and absorption have had thier healing and damage values nerfed now 5 healing and 2 damage respectively. 
- tweak: Changed Incendiary solution now heats the target up more.
- add: Added Stamina solutions now interact with chromium slime.

Solutions tweaks

---

Resources/Prototypes/_CP14/Entities/Objects/Specific/Thaumaturgy/essence.yml
Resources/Prototypes/_CP14/Entities/Structures/Specific/Thaumaturgy/essence_nodes.yml
Resources/Prototypes/_CP14/MagicTypes/magic.yml
Resources/Prototypes/_CP14/Reagents/magic_essence.yml

Terra is now green
Helps people not mix up terra and perditio
**Changelog**
:cl:
- tweak: Changed terra is now green.

grer terra

---

Resources/Prototypes/_CP14/Trading/BuyPositions/guards.yml

Corrects a duplicate ID

---

Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_dagger.yml

Changed the ice dagger's hit sound from thuds to slash
[Issue](https://github.com/crystallpunk-14/crystall-punk-14/issues/1083)
**Changelog**
:cl:
- fix: Ice dagger's hit sound is now a slash

Changed ice dagger's hitsound

---

Content.Shared/_CP14/MagicSpell/CP14SharedMagicSystem.cs

fix client spam from magic

---

Resources/Prototypes/_CP14/Catalog/Fills/closets.yml

Added Tieflings Gambit to the roundstart loot of Innkeepers closet
I have only seen it once and it belonged to someone rules for party games shouldn't be very hard to find especially at the tavern
**Changelog**
:cl:
- tweak: Innkeepers now start with Tiefling's gambit in their closet.

Have games in your closet innkeeper.

---

Content.Client/_CP14/Cooking/CP14ClientCookingSystem.cs
Content.Shared/_CP14/Cooking/CP14SharedCookingSystem.cs

Fixed dissapearing food visuals bug

---

Content.IntegrationTests/Tests/ContrabandTest.cs
Content.IntegrationTests/Tests/GravityGridTest.cs
Content.IntegrationTests/Tests/Lathe/LatheTest.cs
Content.IntegrationTests/Tests/SalvageTest.cs
Content.IntegrationTests/Tests/ShuttleTest.cs
Content.IntegrationTests/Tests/StoreTests.cs
Content.IntegrationTests/Tests/Wires/WireLayoutTest.cs
Content.IntegrationTests/Tests/XenoArtifactTest.cs

we 100% dont wanna use github calculation powers to tests XenoArtifacts or something that we dont use at all

Disable some vanilla integration tests

---

Content.Shared/StatusEffectNew/StatusEffectsSystem.cs
Resources/Prototypes/_CP14/Alerts/status_effect.yml
Resources/Prototypes/_CP14/Entities/Actions/Spells/Light/sphere_of_light.yml
Resources/Prototypes/_CP14/Entities/StatusEffects/misc.yml

:cl:
- tweak: The sphere of light is again applied as a status effect to the specified entity.

Sphere of light returns

---

Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
Resources/Prototypes/_CP14/Entities/Objects/Keys/Catalog/blacksmith.yml
Resources/Prototypes/_CP14/Entities/Objects/Keys/Catalog/merchant.yml
Resources/Prototypes/_CP14/Entities/Objects/Keys/keyrings.yml

TYPO Fixes for key ids

---

Resources/Prototypes/_CP14/Body/Prototypes/carcat.yml
Resources/Prototypes/_CP14/Entities/Mobs/Species/carcat.yml

Каркаты по лору могут есть сырое мясо. Однако до этого у них был человеческий желудок. Теперь у них животный.
**Changelog**
:cl:
- tweak: Carcats can eat raw meat now

Carcats can eat raw meat

---

Content.Shared/_CP14/LockKey/Components/CP14KeyUniversalComponent.cs
Content.Shared/_CP14/LockKey/SharedCP14LockKeySystem.cs
Resources/Locale/en-US/_CP14/lockKey/keyring.ftl
Resources/Locale/ru-RU/_CP14/lockKey/keyring.ftl
Resources/Prototypes/_CP14/Entities/Objects/Keys/key.yml

Adds new key that transform its shape on using it on any lock.
So basically a key that unlock any lock.
For now designed as admin only tool.
For admin purpose and can be given as adminabuse.
https://github.com/user-attachments/assets/15e7bc74-2b13-41c0-bb79-08b713a6af2f
**Changelog**
no cl admin

Add universal key

---

Resources/Prototypes/_CP14/Entities/Structures/Decorations/cobwebs.yml
Resources/Prototypes/_CP14/Entities/Structures/Decorations/flags_wallmount.yml
Resources/Prototypes/_CP14/Entities/Structures/Decorations/statues.yml
Resources/Prototypes/_CP14/Entities/Structures/Decorations/tombstones.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/barrel.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/barrel_crane.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/beds.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/bench.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/bonfire.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/bookshelf.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/cabinets.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/chairs.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/closets.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/curtains.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/furnace.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/lamppost.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/mannequin.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/pallets.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/safe.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/tables.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/torch.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/wallmount_order_border.yml
Resources/Prototypes/_CP14/Entities/Structures/Furniture/workbenchs.yml
Resources/Prototypes/_CP14/Entities/Structures/Storage/Crates/crates.yml

Edits and updates to damageModifierSet for various structures.
Правки и обновление damageModifierSet различных структур.
Sometimes quite strange modifiers for structures.
Иногда довольно странные модификаторы для структур.

Updating damageModifierSet structures

---

Resources/Prototypes/_CP14/Recipes/Workbench/sewing_table.yml

Removal of cloth dupes.
Удаление дюпа ткани.
Fix #1684

No cloth dupe

---

Content.Shared/Light/Components/LightCycleComponent.cs
Content.Shared/Light/Components/SunShadowCycleComponent.cs
Content.Shared/Light/EntitySystems/SharedLightCycleSystem.cs
Content.Shared/_CP14/DayCycle/CP14DayCycleSystem.cs
Content.Shared/_CP14/Random/Rules/CP14IsNight.cs
Resources/Maps/_CP14/venicialis.yml
Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/MapLight/mapLight.yml

fix #1564
:cl:
- tweak: The day now lasts much longer in relation to the night.
- tweak: Even at midnight, the stars still dimly illuminate this cursed world.
- fix: Day and night calculations have been corrected. Vampires no longer burn at night.

Fix daylight

---

Resources/Prototypes/_CP14/Entities/Objects/Weapons/Magic/twoHandedStaffs.yml

Change yml to fix client side animation swing for magic staves (hitboxes work fine before and after).
Fixes #1750
**Changelog**
No changelog necessary, visual change

Fix staff wideswing direction

---

Resources/Prototypes/_CP14/Entities/Mobs/NPC/cats.yml

see above
they're needed to do so
it doesn't need changelog

cats now climb on tables

---

Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs

did what the poll voted on
poll
**Changelog**
poll

poll results

---

Resources/Prototypes/_CP14/Reagents/Target Effects/damage_effects.yml

I added Flamable and heat damage to Incendiary solution 
@KittyCat432 asked me to do it as first time contributer.
**Changelog**
:cl: kin98
- add: Incendiary solution Ignites characters on hit
- tweak: incendiary solution now does 1.5 heat.

Added Flamable and Heat damage to Incendiary reagent
